package(default_visibility = ["//visibility:public"])

cc_binary(
name = "other_test",
srcs = ["other_test.cpp"],
deps = ["//:test_proto_cc",         "@com_google_protobuf//:protobuf",
        "@com_google_protobuf//:protobuf_headers",],
)
